name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # Step 2: Setup the Astro Action
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: . # Adjust if your Astro project is not at the root
          node-version: 20 # Use Node.js version 20
          package-manager: pnpm@8.6.0 # Specify the version of pnpm to use

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

